name: Build Lib
 
on: 
  push:
    branches: 
      - feature/github-ci

jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      with:
          nuget-api-key: ${{secrets.NUGET_API_KEY}}
          nuget-version: 'latest'
     
    - name: Restore NuGet Packages
      run: nuget restore Conspiratio.Lib.sln
 
    - name: Build
      run: msbuild Conspiratio.Lib.sln /p:Configuration=Release
 
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Conspiratio.Lib
        path: Conspiratio.Lib\bin\Release

    - name: Publish the package to nuget.org
      run: nuget push Conspiratio.Lib\*.nupkg ${{secrets.NUGET_API_KEY}} -Source https://api.nuget.org/v3/index.json