name: Push - Build and publish Lib
 
on: 
  push:
    branches: 
      - master

jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      with:
          nuget-api-key: ${{secrets.NUGET_API_KEY}}
          nuget-version: 'latest'
     
    - name: Restore NuGet Packages
      run: nuget restore Conspiratio.Lib.sln
 
    - name: Build
      run: msbuild Conspiratio.Lib.sln /p:Configuration=Release

    - name: nuget Pack
      run: nuget pack Conspiratio.Lib\Conspiratio.Lib.csproj

    - name: Upload Artifacts (DLL)
      uses: actions/upload-artifact@v2
      with:
        name: Conspiratio.Lib DLL
        path: Conspiratio.Lib\bin\Release\Conspiratio.Lib.dll

        - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Conspiratio.Lib
        path: |
          Conspiratio.Lib\bin\Release\*
          *.nupkg

    - name: Publish the package to nuget.org
      run: nuget push *.nupkg ${{secrets.NUGET_API_KEY}} -Source https://api.nuget.org/v3/index.json -SkipDuplicate